apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: 
