apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: result-deployment
  labels:
    app: result-deployment
spec:
  selector:
    matchLabels:
      app: result-deployment
  template:
    metadata:
      labels:
        app: result-deployment
    spec:
      containers:
      - name: result
        image: kodekloud/examplevotingapp_result:before
