apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-service
spec:
  type: NodePort
  selector:
    app: vote-deployment
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
